### ISSUE TITLE
Column mismatch between Synthea Data and OHDSI / ETL-Synthea

### ISSUE THREAD

**Issue by MichaelSchmidt82** [OHDSI/ETL-Synthea#101]
There are a handful of data points generated by the current Synthea project that require additional columns.  For example, when generating allergies.csv from Synthea, columns `system`, `type` among others are not present in our schema.

Here is the current CSV header for allergies (From Synthea):
Reference:  https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#allergies
```
START,
STOP,
PATIENT,
ENCOUNTER,
CODE,
SYSTEM,
DESCRIPTION,
TYPE,
CATEGORY,
REACTION1,
DESCRIPTION1,
SEVERITY1,
REACTION2,
DESCRIPTION2,
SEVERITY2
```

However, we define a subset:
```
create table @synthea_schema.allergies (
start         date,
stop          date,
patient       varchar(1000),
encounter     varchar(1000),
code          varchar(100),
description   varchar(255)
);
```

Even though some of these fields are optional, they break our current implementation.

**Comment by mbernauer** [comment]
@MichaelSchmidt82 do you know of a workaround for this I'm currently running into the same issue. The README doc for this repo lists `SyntheaVersion = 2.7.0` I suspect adhering to this version may solve the issue
