### ISSUE TITLE
readme lacks driver parameter for connection details

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/ETL-Synthea#105]
The example code on the readme is inaccurate. 

Error: The folder location pathToDriver = '' does not exist.Please set the folder to the location containing the JDBC driver.You can download most drivers using the `downloadJdbcDrivers()` function.

**Comment by MichaelSchmidt82** [comment]
Also, you can set the env var `DATABASECONNECTOR_JAR_FOLDER` to point to your driver install IIRC.
