### ISSUE TITLE
TYPE_CONCEPT_IDs

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/ETL-Synthea#108]
I think the TYPE_CONCEPT_IDs need to be updated.

https://ohdsi.github.io/ETL-Synthea/Drug_exposure.html

581452 and 38000177 are no longer standard.

Need to use these:
https://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&standardConcept=Standard&page=1&pageSize=15&query=

**Comment by AnthonyMolinaro** [comment]
@ericaVoss  Thanks Erica, I will fix it.
