### ISSUE TITLE
import cost data

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/ETL-Synthea#111]
import cost data from 
encounters - base_encounter_cost, total_claim_cost
immunizations - base_cost
medications - base_cost, totalcost
patients - healthcare_expsenses / healthcare_coverage - not sure these are relevant as they may just be summaries of other costs?
procedures - base_cost

**Comment by AnthonyMolinaro** [comment]
@fdefalco I've added the initial mapping for COST for synthea v.2.7.0 only.  Version 3.0.0 is quite different and will require some additional testing as we discussed.  I'll have an initial stab at it before pulling Gowtham in.  Please have a look, thanks!

**Comment by AnthonyMolinaro** [comment]
Closed by #146
