### ISSUE TITLE
extend support to synthea 3.0 release

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/ETL-Synthea#119]

**Comment by fabkury** [comment]
+1
I am also unable to run nor build Synthea 2.7.0, due to obscure Java issues. Therefore I can't use ETL-Synthea at all.

**Comment by fdefalco** [comment]
@fabkury - You can download the 2.7 release JAR from the Synthea releases and then run Synthea with the 2.7 release JAR without having to compile.  

If you take a look through this gist you'll see ways of overcoming some of the weird Java issues I've also experienced.

https://gist.github.com/fdefalco/35b7844626a9d8808d99bf5990e46ed2

**Comment by fabkury** [comment]
Thank you, Wade.
