### ISSUE TITLE
Issue importing syntha data into cdm (Incorrect syntax near 'V2')

### ISSUE THREAD

**Issue by sdotter** [OHDSI/ETL-Synthea#129]
Hi @fdefalco 👋 
Peter asked me to tag you for this issue... Hope you can help...

I have an issue importing 1.3M synthea data into CDM...
I also imported 100k synthetic data and that went fine...

![image](https://user-images.githubusercontent.com/11946839/180783442-7be084ac-cfb6-4fc6-9222-35aee971aafd.png)

`> ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails,syntheaSchema,syntheaFileLoc)
Connecting using SQL Server driver
Loading: allergies.csv
  |                                                                                           |   0%java.sql.BatchUpdateException: Incorrect syntax near 'V2'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2085)
	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)
  |==                                                                                         |   2%
 Error in rJava::.jcall(batchedInsert, "V", "setInteger", i, column) : 
java.lang.NullPointerException`

**Comment by fdefalco** [comment]
Is this occurring during the loading of the allergies.csv file?  I checked the source files and V2 or even a capital V do not occur in my versions of the file, can you check to see if you see the same?

**Comment by sdotter** [comment]
Hi Frank! Where did you look? Here at my source it is in databaseConnector...(https://github.com/OHDSI/DatabaseConnector/blob/4832d2080dfd57648c680035a58152fd6e6a9954/R/InsertTable.R#L358) but can it also be that dataset generated isnt correct?

**Comment by fdefalco** [comment]
Ah, my mistake, I was thinking it was an issue with the data file that contained a V, I see now its something to do with database connector's insert.  Perhaps the allergies file has an empty value where one is expected in an integer field?

**Comment by sdotter** [comment]
Yeah i was also thinking about that the dataset maybe contain incorrect data or something... 
I think ill have to try with new generated data and see what happens. Thanks!

**Comment by sdotter** [comment]
Hi Frank! I also tried to upload it with another allergies.csv from 100k dataset (that did imported without errors)...
But then i get an error:

```
Loading: conditions.csv
  |                                                                                                                                      |   0%java.sql.BatchUpdateException: Incorrect syntax near '-'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2085)
	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)
 Error in rJava::.jcall(batchedInsert, "V", "setInteger", i, column) : 
java.lang.NullPointerException
```

**Comment by sdotter** [comment]
Is it possible to regenerate the 1.3M dataset?

**Comment by fdefalco** [comment]
Another theory @AnthonyMolinaro is considering is that the headers from this simulation are missing and that could be the issue.  For this simulation I ran with 4 processes and using the option to append to files.  Perhaps in this mode the headers are omitted.  If you add appropriate headers to the files, this might solve the ETL issue.  As a test, this is the appropriate header for the allergies.csv file:

START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION

**Comment by AnthonyMolinaro** [comment]
@sdotter 
I was able to confirm, the issue is the missing headers. Using the allergies.csv file that @fdefalco sent, I was able to load successfully once the headers were added.  You can use the following to test (update path and the synthea schema name):

```r
allergies.csv <- read.csv("D:/sandbox/allergies/allergies.csv", header = F)

colnames(allergies.csv) <- c("start","stop","patient","encounter","code","description")

allergies.csv$start <- as.Date(allergies.csv$start,format="%Y-%m-%d")
allergies.csv$stop  <- as.Date(allergies.csv$stop,format="%Y-%m-%d")
allergies.csv$code  <- as.character(allergies.csv$code)

conn <- DatabaseConnector::connect(connectionDetails)
DatabaseConnector::insertTable(
	connection     = conn,
	tableName      = "allergies",
	databaseSchema = "synthea_v270",
	data           = allergies.csv,
	dropTableIfExists = F,
	createTable       = F,
	bulkLoad          = T
)
DatabaseConnector::disconnect(conn)
```

578713 rows were loaded in a few secs using bulk loading.

**Comment by sdotter** [comment]
H Anthon!
Thanks for helping! Right now i was able to also continue with a quick and dirty way... set cohort_name to allow NULL in concepts table.
But when this is finished ill do this for the next dataset your way...

About the missing headers are the "start","stop","patient","encounter","code","description"? 

And besided this issue; bulk loading? i'm very curious 👍 

Thanks again!

**Comment by AnthonyMolinaro** [comment]
@sdotter 
Yes, those are the missing headers.  Btw, they correspond to the table column names (good to know in case you hit this with other tables):

https://github.com/OHDSI/ETL-Synthea/blob/master/inst/sql/sql_server/synthea_version/v270/create_synthea_tables.sql

Good luck, keep us posted!

**Comment by sdotter** [comment]
![image](https://user-images.githubusercontent.com/11946839/181816468-3daa9a52-ebc6-4924-8da4-3ea2ab54a12b.png)
Well no luck for now... 
Im gonna try again on other workstation

**Comment by sdotter** [comment]
Hi guys! Hope that you can help me out with the next one:

`Loading: conditions.csv
  |                                                                                                                                      |   0%java.sql.BatchUpdateException: Incorrect syntax near '-'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2085)
	at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)`

Im kinda lost :(

**Comment by sdotter** [comment]
Again two other errors and warning:

![image](https://user-images.githubusercontent.com/11946839/182097226-b74398d7-4b1b-4f16-b54d-73bab3256eb7.png)

**Comment by AnthonyMolinaro** [comment]
@sdotter 
Hi, are you running the "quick and dirty way" you mentioned last week or did you add headers to each of the csv files?  The R code expects ALL csv files to have headers, so if they are not there, they should be added.  Let me know if you need a hand identifying what the headers are for each csv.

**Comment by sdotter** [comment]
Hi Anthony!

Yeah i added the headers (just another way)

`sed -i '1s/^/START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION\n/' allergies.csv
sed -i '1s/^/Id,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION\n/' careplans.csv
sed -i '1s/^/START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION\n/' conditions.csv
sed -i '1s/^/START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,UDI\n/' devices.csv
sed -i '1s/^/Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION\n/' encounters.csv
sed -i '1s/^/Id,DATE,PATIENT,ENCOUNTER,SERIES_UID,BODYSITE_CODE,BODYSITE_DESCRIPTION,MODALITY_CODE,MODALITY_DESCRIPTION,INSTANCE_UID,SOP_CODE,SOP_DESCRIPTION,PROCEDURE_CODE\n/' imaging_studies.csv
sed -i '1s/^/DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST\n/' immunizations.csv
sed -i '1s/^/START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION\n/' medications.csv
sed -i '1s/^/DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,VALUE,UNITS,TYPE\n/' observations.csv
sed -i '1s/^/Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON,PHONE,REVENUE,UTILIZATION\n/' organizations.csv
sed -i '1s/^/Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE\n/' patients.csv
sed -i '1s/^/PATIENT,START_YEAR,END_YEAR,PAYER,OWNERSHIP\n/' payer_transitions.csv
sed -i '1s/^/Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE,AMOUNT_COVERED,AMOUNT_UNCOVERED,REVENUE,COVERED_ENCOUNTERS,UNCOVERED_ENCOUNTERS,COVERED_MEDICATIONS,UNCOVERED_MEDICATIONS,COVERED_PROCEDURES,UNCOVERED_PROCEDURES,COVERED_IMMUNIZATIONS,UNCOVERED_IMMUNIZATIONS,UNIQUE_CUSTOMERS,QOLS_AVG,MEMBER_MONTHS\n/' payers.csv
sed -i '1s/^/DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION\n/' procedures.csv
sed -i '1s/^/Id,ORGANIZATION,NAME,GENDER,SPECIALITY,ADDRESS,CITY,STATE,ZIP,LAT,LON,UTILIZATION\n/' providers.csv
sed -i '1s/^/DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,QUANTITY\n/' supplies.csv`

Pretty fast for even 50GB CSV file haha
