### ISSUE TITLE
Cancer ETL

### ISSUE THREAD

**Issue by priagopal** [OHDSI/ETL-Synthea#130]
Hi,

I am working on Cancer ETL. What is the best order to follow in populating domain?

Episode
Episode_event
Condition_occurrence
procedure
drug_exposure
Measurement (link to condition_occurrence)

Does the above order seem reasonable?

Thanks,
Priya

**Comment by clairblacketer** [comment]
Hi Priya, I would actually put EPISODE and EPISODE_EVENT at the bottom of your list. They are meant to group facts from CONDITION_OCCURRENCE, PROCEDURE_OCCURRENCE, DRUG_EXPOSURE and MEASUREMENT into episodes of care. I think this presentation gives a good overview of how these tables work together.

https://github.com/OHDSI/CommonDataModel/files/2642492/Oncology.CDM.Proposal.2018-12-02.pdf

**Comment by priagopal** [comment]
Hi Clair,

Thanks so much. I will review the presentation.

Thanks
Priya

**Comment by priagopal** [comment]
Hi Team,

The presentation provided is very useful. Claire, Thanks so much. For mapping conditions and measurement, I noticed that in Synthea data, the conditions have SNOMED CT . It is not in ICD-O. I can map the SNOMED as such right? I need to modify the measurement table to include modifier_id and modifier_event_id and link the measurement records and corresponding conditions. Is my understanding right? 

Thanks,
Priya

**Comment by clairblacketer** [comment]
Hi Priya, you are correct :) you will need to modify the measurement table as you say and you can definitely use SNOMED for this example.

**Comment by priagopal** [comment]
Hi Clair,

Thanks again. I am planning to create temp tables to populate condition, procedures, drug, measurement, episode and episode_event. I pulled out some data from Synthea and mapped it out on spreadsheet as per my understanding. I have quite a few questions. I am not sure, how to programmatically identify cancer conditions, procedures , drugs or measurements? If you have any insights please share. 

For measurement, I believe I should map the measurement.event_id with condition_occurrence_id and the modifier_id with corresponding episode_id? I am not sure, if that is the right approach.

Please check the spreadsheet and provide your insights. Thanks so much.

Priya
[questions.xlsx](https://github.com/OHDSI/ETL-Synthea/files/9436199/questions.xlsx)

**Comment by priagopal** [comment]
Hi Claire,
I have created measurement temp table with record_id and modifier_field_Concept_id for cancer related conditions that has measurements related to size, grade, stage etc., Can you please take a look and let me know, if my approach is right? I have included the sql script, the measurement temp table output , the source data and OMOP condition_occurrence table. 

After you confirm, I can start working on episodes.

Thanks,
Priya
[questions.zip](https://github.com/OHDSI/ETL-Synthea/files/9463528/questions.zip)

**Comment by cgreich** [comment]
Very nice, @priagopal. Almost perfect. 

You are using LOINC concepts for the cancer modifiers. But we created a new vocabulary called Cancer Modifier. For example, you use [Regional lymph nodes.clinical [Class] Cancer](https://athena.ohdsi.org/search-terms/terms/3007727). Instead, you should use [Regional Lymph Nodes](https://athena.ohdsi.org/search-terms/terms/36769269).

**Comment by priagopal** [comment]
Hi Christian,

Thanks so much for your review. I can update the ETL script after the regional lymph nodes are available in the concept table. I think, I might have to do the same for other finding values related to cancer that are mapped to LOINC instead of cancer modifier (e.g: distant metastases). 

I was thinking, if I could create the draft EPISODE and EPISODE_EVENT ETL scripts for the Synthea data. With the understanding, some of the concept information might change based on the updates made to the standard concepts.

Please let me know, if this is an acceptable approach.

Thanks,
priya

**Comment by cgreich** [comment]
I know. We feel guilty pulling the carpet while you are on it. But it sounds worse than it is.

Do you have a list of source codes you want to capture as Cancer Modifiers or Episodes?

**Comment by priagopal** [comment]
Hi Christian,

I have attached the distinct cancer modifiers. Based on the data, the episodes are first occurrence, treatment cycle and cancer surgery. 

Please let me know, if you need any other information.

Thanks so much for your help.

Priya

[CancerModifier.csv](https://github.com/OHDSI/ETL-Synthea/files/9473703/CancerModifier.csv)

**Comment by priagopal** [comment]
Hi Christian/Claire,

In the example below, the condition records related to first occurrence, relapse, remission and included in EPISODE domain.  But, in Athena, the above concepts are invalidated. I wasn't sure whether I model only treatment abstractions in episode domain and not condition abstraction?

I was referring to the attached presentation to understand Episode mapping. 
[Oncology.CDM.Proposal.2018-12-02 (2).pdf](https://github.com/OHDSI/ETL-Synthea/files/9483062/Oncology.CDM.Proposal.2018-12-02.2.pdf)

Thanks,
priya
