### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by reiffsb** [OHDSI/ETL-Synthea#131]
I saw that there have been updates to map providers.csv to provider and devices.csv to device_exposure - are there any plans to update the documentation available on [https://ohdsi.github.io/ETL-Synthea/articles/](https://ohdsi.github.io/ETL-Synthea/articles/)? I think it would be very helpful. 

I mentioned provider and device_exposure specifically because I saw those had been added while browsing past issues, but if any additional tables are mapped that aren't documented on the github pages site it would be great to see those included as well.

**Comment by burrowse** [comment]
@reiffsb Thank you for the feedback! New documentation for the device_exposure, provider, visit_detail,payer_plan_period and cost tables has been added. This documentation will be further updated and improved as more features are added to the package.
