### ISSUE TITLE
Error during LoadEventTables

### ISSUE THREAD

**Issue by avtaylor** [OHDSI/ETL-Synthea#139]
This is using the instructions for loading the Synthea ETL to OMOP using R: https://ohdsi.github.io/ETL-Synthea/index.html

I get several errors related to primary keys. The first is for the VISIT_OCCURRENCE table.
When I run the ETL logic - the SQl that fails gets saved in the error log file - indeed I see several records that are the same - so maybe a group by is missing? 
However, because I am not re-building the whole code I opted for dropping pk  constraints, upload the data, then clean the tables, then add back the pks? What is the solution?

A related question is what is the impact of not having the pk contraints on the  VISIT_OCCURRENCE table and other tables?
Would this affect the way the WebApi will access data and also the ATLAS dashboards?

I am asking this because I managed to upload synthea and I connected the sources with the WebAPI but on ATLAS I get no data being pulled from the DB or displayed. What could be the reasons?

**Comment by fdefalco** [comment]
Can you please share the error log?  Could you also please share the commands you are using to generate the Synthea data?

**Comment by burrowse** [comment]
Closing! @avtaylor please reopen and more detail (commands and error log) if the issue persists.
