### ISSUE TITLE
Is LoadEventTables (from the documentation) now LoadCDMTables?

### ISSUE THREAD

**Issue by turbomam** [OHDSI/ETL-Synthea#14]
I struggled to run the synthea-to-OMOP CDM conversion on a Windows 10 computer, using Postgres 11 and R 3.5.0.  I see there have been a lot of commits in the last day or so.  Is it possible that there's a mismatch between the latest commit and the documentation?  Should I pull a different commit, or from a different branch?

At roughly 2019-03-16-13:00 EDT, I did the following

> git clone https://github.com/OHDSI/ETL-Synthea.git

(in GitBash) and ran synthea like this

> ./run_synthea -s 42 -p 1000 Massachusetts

And then attempted the conversion according to https://github.com/OHDSI/ETL-Synthea#step-by-step-example-r-package.  See #13 for some modifications I made to date casting and allowing NULLs.  Now everything runs with just a few warnings, up until the last step: `ETLSyntheaBuilder::LoadEventTables(cd,"cdm_synthea10","native")`, which gives

> Error: object 'LoadEventTables' not found

I've already called `LoadSyntheaTables` and `LoadVocabFromCsv `.  `LoadVocabFromSchema` isn't necessary on top of `LoadVocabFromCsv `, is it?  So I just used the remaining load function instead: 
 `LoadCDMTables`.  That completed without any intervention or any errors, but with the following warnings:

> Running: insert_drug_era.sql
> ...snip... 100% ... Executing SQL took 0.0229 secs

> 1: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL

> 2: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL

> 3: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'synthea_schema' not found in SQL

> 4: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL

> 5: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'synthea_schema' not found in SQL

> 6: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL

> 7: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'synthea_schema' not found in SQL
`LoadCDMTables`.  That's running on `insert_measurement.sql`now, without any intervention. 

----

I also tried the Windows batch command, which seems to give a similar error

> C:\Users\Mark Miller\ETL-Synthea>"C:\Program Files\R\R-3.5.0\bin\x64\Rscript.exe" WindowsLoader.r postgresql localhost ehrlike native cdm_synthea10 postgres SECRETPASSWORD C:\synthea_omop\synthea_output_csv C:\synthea_omop\vocabulary_downloads

> Error: 'DropCDMTables' is not an exported object from 'namespace:ETLSyntheaBuilder'

I'm willing to recreate my environment in Ubuntu, if that's the best bet, but I don;t get the feeling that this issue is OS related.

**Comment by AnthonyMolinaro** [comment]
@turbomam 

Apologies for getting to this so long after you posted this, Mark., This has been corrected in Master.  LoadEventTables is the function name and the LoadEventTables.r file has been updated to reflect that.

Thanks!
