### ISSUE TITLE
Errors during Load Vocabularies

### ISSUE THREAD

**Issue by avtaylor** [OHDSI/ETL-Synthea#140]
There are errors during the loading of vocabularies due to Null values in the concepts csv file for the firls concept_name (a few fields are na) and the constraints on the table concepts does not allow NULL for that field.

A related question: will it work to load the vocabulary tables in a separate schema? and then use these across several OMOP sources? Say have syngthea data and anothe omop data in the same database in separate schema both using the same vocabularies?

**Comment by fdefalco** [comment]
All concepts must have the concept_name field populated.  Ensure your vocabulary files are valid before loading.  

It is a requirement that each CDM schema contains the vocabulary tables loaded with content to be considered a valid CDM that will work across all OHDSI tools.
