### ISSUE TITLE
Atlas reports - many are just empty including Dashboard

### ISSUE THREAD

**Issue by avtaylor** [OHDSI/ETL-Synthea#142]
What I have done: I uploaded Synthea with 1000 patients. I uploaded using the R code provided. I then run the Achilles command.

Atlas configuration as shown. 
**The reports are empty showing NO DATA:** dashboard, visit, condition era, 

**Reports that work showing data:** Person, Data density, Drug exposure, drug era, 

**Partly working**: condition_occurrence, procedure have several NA values as in attachment. Observation(? as per image), death (does not have data for aggregates per age or gender)

Achilles Heel - Error showing report

Are these as expected - what is wrong and how to generate data for these reports that do not show any data. Thank you.

![image](https://user-images.githubusercontent.com/20873498/197620830-ffcba694-d230-46d6-a146-16dffc33e3a0.png)
![image](https://user-images.githubusercontent.com/20873498/197621608-36720c2c-4554-4839-9a5a-313146f10390.png)
![image](https://user-images.githubusercontent.com/20873498/197622164-69f6b301-d3ba-4803-ae02-022be9b71beb.png)

**Comment by fdefalco** [comment]
The ETL-Synthea repository converts data from the Synthea export CSV files and converts it to the Common Data Model format.  Issues with ATLAS should be raised in the https://github.com/ohdsi/atlas repository.  

Other tips:
Ensure you have the latest version of the Achilles package, as it has received major updates over the past 6 months.
The Achilles Heel report has been deprecated and Achilles will no longer generate data for this report.

An alternative would be to follow the instructions and use the https://github.com/ohdsi/ares tool to test the output from Achilles.

**Comment by avtaylor** [comment]
Noted re Achilles Heel
I do have the latest version of the Achilles package. 
Just a question please before closing this: what could cause the DASHBOARD to be empty?
