### ISSUE TITLE
ETL LoadEventTables

### ISSUE THREAD

**Issue by Ryan-nd** [OHDSI/ETL-Synthea#150]
Hello,

 Would like to address the same issue with loading the condition occurrence as it is taking a long time to process as compared to the  insert visit occurrence, visit details table. Attached the first picture (Conditions table), 2nd photo is the processing. Do appreciate if any insights could be given. 
<img width="661" alt="omop convertion 2" src="https://user-images.githubusercontent.com/85671367/205797464-7306d644-16f5-4968-be99-559e70492767.png">
<img width="866" alt="omop convertion 1" src="https://user-images.githubusercontent.com/85671367/205797514-8a8349e0-9b82-4b12-be84-756acbab3912.png">

**Comment by Ryan-nd** [comment]
Hi Frank,

Thanks for the fast response! Would you say its because of Athena Dictionary that affects the performance of my ETL as I uploaded 5GB worth of Data and 1k of Synthetic Data. Appreciate the insights given!

Regards,
Ryan Li

**Comment by fdefalco** [comment]
That is possible.  I'm working on a new ETL artifact standard to try and help with questions just like this and will let you know when there is some progress there.  The best thing I could suggest would be doing an explain plan on the insert statement causing the delay and see if there are any particular issues.  Perhaps indexes on the vocabulary tables are missing?

**Comment by Ryan-nd** [comment]
Ooh alright. Will do, appreciate the help and quick reponse that was given! 

Regards,
Ryan Li
