### ISSUE TITLE
actual 1000 people demo data

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/ETL-Synthea#16]
This how to guide is valuable. Thank you for doing it.

For our group, however, having a set of CSV files (or postgres dump file (way more preferred)) with the final product would help much more.

Consider starting a second repo that would have that. 
I don't think synthea puts any restrictions such that this would not be possible to do.

That way the fruit of your labor would be used by a lot more people! tagging @clairblacketer

**Comment by fdefalco** [comment]
Our intention is to make that sample data part of the Eunomia package, which will include a SqLite database file that can be used from within R along with all the OHDSI tools to perform studies.  We're currently working on custom Synthea modules that introduce confounding and drug effects that will enable example studies using CohortMethod.

**Comment by vojtechhuser** [comment]
Can you share the SQL lite file earlier than that. We don't need pertubed data but do need better than SynPuf Demo data.

**Comment by fdefalco** [comment]
A sample dataset has now been provided in the Eunomia package.

https://github.com/OHDSI/Eunomia
