### ISSUE TITLE
github.io example code out of date

### ISSUE THREAD

**Issue by katy-sadowski** [OHDSI/ETL-Synthea#164]
The Step by Step example code [here](https://ohdsi.github.io/ETL-Synthea/) states `we currently only support version 2.7.0`; however the code in the README says that 3.0.0 is supported.

**Comment by katy-sadowski** [comment]
(also noting i initially tried building Synthea from v2.7.0 but ran into some java versioning issues which were fixed in a later release)

**Comment by burrowse** [comment]
Thanks for alerting us of this issue @katy-sadowski ! The documentation is now up to date [here](https://ohdsi.github.io/ETL-Synthea/) with the current synthea version offerings. We are starting to work on updating the package to support newer releases so more updates will be forthcoming.
