### ISSUE TITLE
Bug  - redundant self join in AllVisitsTable.sql

### ISSUE THREAD

**Issue by egillax** [OHDSI/ETL-Synthea#180]
The self join in this [line](https://github.com/OHDSI/ETL-Synthea/blob/main/inst/sql/sql_server/cdm_version/v540/AllVisitTable.sql#L81) is not doing anything.

I'm not sure what it is supposed to do, above it it says: 
```sql
/* Emergency visits */
/* collapse ER claim lines with no days between them into one visit */
```

**Comment by burrowse** [comment]
Thank you @egillax ! I've identified a fix and this will be addressed in the upcoming release.
