### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by Zachary-Higgins** [OHDSI/ETL-Synthea#183]
Hi - We're new to this project, and wanted to provide some feedback that may help others. Could you please consider adding some additional instructions to the Readme.

After  `CreateCDMTables` has been called, please consider adding
```r
ETLSyntheaBuilder::CreateVocabMapTables(connectionDetails = cd, cdmSchema = cdmSchema, cdmVersion = cdmVersion)
```

And after `LoadSyntheaTables` has been called, please consider adding
```r
ETLSyntheaBuilder::CreateVisitRollupTables(connectionDetails = cd, cdmSchema = cdmSchema, cdmVersion = cdmVersion, syntheaSchema = syntheaSchema)
```

We have some PR's we'd like to submit regarding Databricks compatibility. It's not really related, but I can include the changes in there if you think its OK?

Thanks!

**Comment by burrowse** [comment]
Thanks for the feedback @Zachary-Higgins! We are preparing for a release that will include updated instructions and additional features in the next week or two. These changes are present on the [develop branch](https://github.com/OHDSI/ETL-Synthea/tree/develop). Regarding PRs for databricks, yes please! We welcome contributions to the package :) Thank you!
