### ISSUE TITLE
Is this still being maintained? Synthea is at version 3.6.2 and this only supports 3.0.0?

### ISSUE THREAD

**Issue by thondeboer** [OHDSI/ETL-Synthea#184]
Tried to use this on the latest Synthea release (3.6.2) but got errors on loading person, since the FIPS field seems to be added for a person, but Sythea-ETL does not support this...So, do we have to downgrade to Synthea 3.0.0 for this to work?

**Comment by burrowse** [comment]
@thondeboer Thanks for reaching out! For current use of the package, yes you would need to use [Synthea v3.0.0](https://github.com/synthetichealth/synthea/releases/tag/v3.0.0).

According to the [Synthea Github release tags](https://github.com/synthetichealth/synthea/releases) the latest official release is v3.2.0. The Synthea master branch is a moving target so we try to support official releases for the development of the ETL-Synthea package. Can you provide more information on where you are seeing 3.6.2 as the latest release? 

We are currently preparing a 2.0 release of ETL-Synthea to support versions 3.1.0 and 3.2.0 [here](https://github.com/OHDSI/ETL-Synthea/pull/185). We hope to have these updates available soon for use.

With regards to the FIPS field from the synthea patients domain, that is not a field that is in the CDM at the person or location level. We would welcome a community contribution to bring this field into the ETL based on your use-case.

**Comment by burrowse** [comment]
Updates to the package to support Synthea v3.1.0 and Synthea v3.2.0 have been deployed!

**Comment by thondeboer** [comment]
Great ...I was about to do a PR for my changes to the same effect :) But glad to see the update...
