### ISSUE TITLE
error when running codeToRun

### ISSUE THREAD

**Issue by ginberg** [OHDSI/ETL-Synthea#190]
I noticed when running the script that [these lines](https://github.com/OHDSI/ETL-Synthea/blob/main/extras/codeToRun.R#L37-L39) are not working since a couple variables are not defined and 'CreateExtraIndices' does not have a parameter cmdVersion.

Replacing it by code below fixes it:
```
ETLSyntheaBuilder::CreateMapAndRollupTables(connectionDetails, cdmDatabaseSchema, syntheaSchema, cdmVersion, syntheaVersion)
## Optional Step to create extra indices
ETLSyntheaBuilder::CreateExtraIndices(connectionDetails, cdmDatabaseSchema, syntheaSchema, syntheaVersion)
```

**Comment by burrowse** [comment]
Thanks for reporting this @ginberg ! The codeToRun file has been updated!
