### ISSUE TITLE
Bulk load script needs documentation for execution.

### ISSUE THREAD

**Issue by zeronoun** [OHDSI/ETL-Synthea#2]
Script structure is shown as:
`# ./bulk-load database native cdm user password /path/to/data /path/to/vocab`

With an example of:
`# ./bulk-load cdm2 ohdsi ohdsi /synthea/output/csv`

The _/path/to/vocab_ is easy to sort out, but what are the _native_ and _cdm_ parameters?

**Comment by AnthonyMolinaro** [comment]
@zeronoun Good catch, it's not obvious. I'll add some comments to the script so it's clear.  In the meantime, I'll explain here.  The params, native and cdm, indicate the names of the db schemas to load your synthea data and cdm data, respectively (the idea being, you may not necessary want to load them into the same schema).  If you're putting the synthea and cdm tables into the same schema, then native = cdm.  For example, postgres has a default "public" schema.  To use a database called "my_synthea" and load both the synthea tables and cdm tables into the "public" schema, you'd use:

```
./bulk-load my_synthea public public user pw '/Path to synthea csv files' '/Path to vocabulary csv files'
 ```
Perhaps just changing the parameter names from native and cdm to to synthea_schema and cdm_schema, would make it more clear as well.

**Comment by zeronoun** [comment]
> Perhaps just changing the parameter names from native and cdm to to synthea_schema and cdm_schema, would make it more clear as well.

I think that's a great idea.
Thank you for your quick response!

**Comment by AnthonyMolinaro** [comment]
Updated as per our discussion, thanks again!
