### ISSUE TITLE
ETLSyntheaBuilder::CreateSyntheaTables failing for oracle19c ADW with java.sql.SQLSyntaxErrorException: ORA-00904: : invalid identifier 

### ISSUE THREAD

**Issue by dwijen** [OHDSI/ETL-Synthea#205]
using this config
```
cdmSchema      <- "SYNTHEA"
cdmVersion     <- "5.4"
syntheaVersion <- "3.3.0"         #"2.7.0"
syntheaSchema  <- "NATIVE"
syntheaFileLoc <- "C:/OMOP/output/csv"
vocabFileLoc   <- "C:/OMOP/vocabulary"
```
and when executing below code - 
`ETLSyntheaBuilder::CreateSyntheaTables(connectionDetails = cd_oracle, syntheaSchema = syntheaSchema, syntheaVersion = syntheaVersion)`

it's failing with below error - 
`java.sql.SQLSyntaxErrorException: ORA-00904: : invalid identifier
`

As per my exploration it's failing when trying to execute the [create_synthea_tables.sql](https://github.com/OHDSI/ETL-Synthea/blob/main/inst/sql/sql_server/synthea_version/v330/create_synthea_tables.sql
)
as the reason is this line -> https://github.com/OHDSI/ETL-Synthea/blob/main/inst/sql/sql_server/synthea_version/v330/create_synthea_tables.sql#L4

start seems like a reserve word and if I copy the table creation code and run it in oracle  sql editor it fails with same error.
keeping the start inside double quotes works fine, it seems need to put all start and other reserve words in double quotes.

the below works fine - 

```
create table test.allergies (
"start"        date,
stop         date,
patient      varchar(1000),
encounter    varchar(1000),
code         varchar(100),
system       varchar(255),
description  varchar(255),
"type"       varchar(255),
category     varchar(255),
reaction1    varchar(255),
description1 varchar(255),
severity1    varchar(255),
reaction2    varchar(255),
description2 varchar(255),
severity2    varchar(255)
);
```

but this fails with `java.sql.SQLSyntaxErrorException: ORA-00904: : invalid identifier

```
create table test.allergies (
start        date,
stop         date,
patient      varchar(1000),
encounter    varchar(1000),
code         varchar(100),
system       varchar(255),
description  varchar(255),
"type"       varchar(255),
category     varchar(255),
reaction1    varchar(255),
description1 varchar(255),
severity1    varchar(255),
reaction2    varchar(255),
description2 varchar(255),
severity2    varchar(255)
);
```

**Comment by burrowse** [comment]
@dwijen Thank you for bringing this to our attention. We have added support for this in the main branch of ETL-Synthea

**Comment by dwijen** [comment]
@burrowse It's still failing for me with this change from `main` branch .
Would you mind to test it by running the below steps and let me know it is working for you or not.


ETLSyntheaBuilder::CreateCDMTables(connectionDetails = cd, cdmSchema = cdmSchema, cdmVersion = cdmVersion)
                                     
ETLSyntheaBuilder::CreateSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaVersion = syntheaVersion)
                                       
ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaFileLoc = syntheaFileLoc)
                                     
ETLSyntheaBuilder::LoadVocabFromCsv(connectionDetails = cd, cdmSchema = cdmSchema, vocabFileLoc = vocabFileLoc)

ETLSyntheaBuilder::CreateMapAndRollupTables(connectionDetails = cd, cdmSchema = cdmSchema, syntheaSchema = syntheaSchema, cdmVersion = cdmVersion, syntheaVersion = syntheaVersion)

**Comment by burrowse** [comment]
@dwijen Apologies for the delay in getting back to you! The fix for this issue introduced another bug. This should now be resolved.
