### ISSUE TITLE
ETL scripts need both schemas on search path?

### ISSUE THREAD

**Issue by turbomam** [OHDSI/ETL-Synthea#27]
I can't get the bulk load script to complete without either

- replacing the `search_path` declaration of `$CDM` with `$CDM,$NATIVE` in all of the steps after "creating visit logic tables"
- OR using the same schema for both the native Synthea tables, as well as the OMOP-shaped tables, in the bulk loader invocation:

`./bulk-load synthea10 127.0.0.1 cdm_synthea10 cdm_synthea10 USERNAME PASSWORD /synthea_data_path /omop_voacb_path`

**Comment by fdefalco** [comment]
Yes, that makes sense.  I think we made the assumption that the synthea and cdm tables would be in the same schema.  Its also the case that we're not actively using the bulk-load script and instead are running using the R package approach.  Would you like to submit a pull request with your recommended changes?

**Comment by AnthonyMolinaro** [comment]
Thanks for all the great contributions here Mark and apologies for being slow to respond at times.  We've deprecated use of the shell script and recommend everyone use the R package now. We'll update the readme to reflect this decision.

**Comment by turbomam** [comment]
Thanks @fdefalco , @AnthonyMolinaro  and colleagues for all of the great responses to this issue, and others I have submitted in the past. I'll try again soon and send feedback or pull requests.

Here's the related work that I presented to the International Conference on Biomedical Ontologies: https://drive.google.com/file/d/1eYXTBl75Wx3XPMmCIOZba-8Cv0DIhlRq/view

**Comment by Tinegeldof** [comment]
Is it possible that these remains an issue even in the R scripts? When passing two schemas as an argument to the SqlRender::render function, warnings/errors appear:

**ETLSyntheaBuilder::CreateVisitRollupTables(cd,"cdm_synthea10","native")**
`Warning message:
In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema) :
  Parameter 'synthea_schema' not found in SQL`

**ETLSyntheaBuilder::LoadEventTables(cd,"cdm_synthea10","native")**
`Error executing SQL:
org.postgresql.util.PSQLException: ERROR: column "provider_id" is of type integer but expression is of type text
  Hint: You will need to rewrite or cast the expression.
  Position: 665
An error report has been created at  /Users/tine.geldof/errorReport.txt
In addition: Warning messages:
1: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL
2: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL
3: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'synthea_schema' not found in SQL
4: In SqlRender::render(sqlQuery, cdm_schema = cdmDatabaseSchema, synthea_schema = syntheaDatabaseSchema,  :
  Parameter 'vocab_schema' not found in SQL`

**Comment by turbomam** [comment]
@Tinegeldof My colleague Hayden has been running these scripts again recently. I'll ask him whether this issue still affected him.
