### ISSUE TITLE
Missing primary key constraint on concept_synonym table

### ISSUE THREAD

**Issue by aspedrosa** [OHDSI/ETL-Synthea#30]
[cdm_v5.3_indexes_ddl.sql](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/cdm_v5.3_indexes_ddl.sql#L56)

**Comment by fdefalco** [comment]
My understanding is that concept_synonym doesn't have a primary key, although it does have a unique constraint.  At least that is my understanding from the CommonDataModel repository.
