### ISSUE TITLE
Map unit_concept_id coming from the observations table

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/ETL-Synthea#35]
There are units available in the native observations table that are not being mapped to a unit_concept_id in the MEASUREMENT table.

**Comment by AnthonyMolinaro** [comment]
Fixed applied, thanks Clair!

**Comment by AnthonyMolinaro** [comment]
Needed to reopen this and change the join to source_to_source_vocab_map, since Synthea already using SNOMED and RxNorm, all the concepts are standard and source_to_concept_map is empty.
