### ISSUE TITLE
Conditions not getting mapped to 0

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/ETL-Synthea#36]
### Expected behavior
The majority of the source codes are mapped to concepts.

### Actual behavior
About 63% of the codes are mapped to 0.  It looks like some values are coming across as descriptions rather than ICD10 codes.  We need to figure out how to get these mapped.

```
SELECT '0 RECORDS' AS TYPE, COUNT(*) ROW_COUNT
FROM CONDITION_OCCURRENCE
WHERE CONDITION_CONCEPT_ID =0
UNION ALL
SELECT 'ALL RECORDS' AS TYPE, COUNT(*) ROW_COUNT
FROM CONDITION_OCCURRENCE
```
0 RECORDS = 4942
ALL RECORDS = 8120

![image](https://user-images.githubusercontent.com/6305439/64461158-6819c000-d0ca-11e9-8205-4f77bb9ae88c.png)

**Comment by cgreich** [comment]
The descriptions are already SNOMEDs. But you need to cut off the concept classes in parenthesis (disorder) etc.

**Comment by fdefalco** [comment]
This issue was used as an example as part of a tutorial session and does not need to be addressed.
