### ISSUE TITLE
extra data after last expected column

### ISSUE THREAD

**Issue by ATianmm** [OHDSI/ETL-Synthea#37]
when I run ./bulk-load, it report some errros like this:

loading data from synthea csv files to relational database
COPY 526
COPY 3521
COPY 8551
ERROR:  extra data after last expected column
CONTEXT:  COPY encounters, line 2: "465dbc2e-ee30-418b-a3f8-f08f48479804,1977-11-19T06:59:41Z,1977-11-19T07:59:41Z,8ea2abeb-ef06-4691-98..."
COPY 14420
ERROR:  extra data after last expected column
CONTEXT:  COPY medications, line 2: "1993-02-11,,8ea2abeb-ef06-4691-98f8-fff89980afd7,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,c39b240b-763b-..."
COPY 282826
ERROR:  extra data after last expected column
CONTEXT:  COPY patients, line 2: "8ea2abeb-ef06-4691-98f8-fff89980afd7,1974-11-19,,999-91-8917,S99914151,X46842681X,Mr.,Marion502,Thie..."
COPY 36850

I check the schema's tables, find that the table  encounters  columns BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE have add as cost
![image](https://user-images.githubusercontent.com/44718121/64673844-dd5a0c00-d4a1-11e9-95a2-8ff257fabbd6.png),

how can I solve this

**Comment by ATianmm** [comment]
the table patients 
![image](https://user-images.githubusercontent.com/44718121/64674110-7d179a00-d4a2-11e9-8c28-3400530f4a00.png)
it doesn't include columns  
STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE

**Comment by AnthonyMolinaro** [comment]
This is been addressed add merged into Master.  Thank you.
