### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mizu99super** [OHDSI/ETL-Synthea#38]
When I execute this code, I get error like database "synthea10" does not exist...
Do I have to do some preparation in advance?

./bulk-load **synthea10** localhost native cdm_synthea10 postgres lollipop /tmp/synthea/output/csv /tmp/Vocabulary_20181119

**Comment by AnthonyMolinaro** [comment]
Hi, this is from the README just below the code you reference:

>  The example above loads into a PostgreSQL database called synthea10.  The schema to load the Synthea tables is native.
>  The schema to load the Vocabulary tables is cdm_synthea10.  The username and pw are postgres and lollipop.
>  The Synthea and Vocabulary CSV files are located in /tmp/synthea/output/csv and /tmp/Vocabulary_20181119, respectively.

Implicit in the code you reference is the existence of the items in the code.  I'm pasting this here because we are phasing out the bulk loader and will only be supporting the R version.
