### ISSUE TITLE
Visit_Occurrence_id in event tables should use the final_visit_ids intermediate table

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/ETL-Synthea#4]
- [Line 53](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_condition_occurrence.sql#L53) of the condition_occurrence insert 
 - [Line 68](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_drug_exposure.sql#L68) of drug_exposure
 - [Line 113](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_drug_exposure.sql#L113) of drug_exposure
- [Line 159](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_drug_exposure.sql#L159) of drug_exposure
 - [Line 62](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_measurement.sql#L62) of measurement
 - [Line 104](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_measurement.sql#L104) of measurement
- [Line 58](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_observation.sql#L58) of observation
- [Line 98](https://github.com/OHDSI/ETL-Synthea/blob/master/ETL/SQL/insert_observation.sql#L98) of observation

These are all joining to visit_occurrence to get the visit_occurrence_id. This is incorrect as not every encounter_id will be represented in visit_occurrence due to how we collapse encounters to create visits (page 3 of design document). Instead, the join should be to the final_visit_id table created to link all encounters with their correct visit_occurrence_id.

**Comment by AnthonyMolinaro** [comment]
Thanks @clairblacketer, good catch!  I'll correct this asap.

**Comment by AnthonyMolinaro** [comment]
@clairblacketer Just pushed the fixes.
