### ISSUE TITLE
[Error] CONTEXT: COPY xxxxx

### ISSUE THREAD

**Issue by mizu99super** [OHDSI/ETL-Synthea#40]
Whats my problem?
How to solve The errors below?

CONTEXT:  COPY encounters, line 2: "99edd026-a004-4b3f-9e91-23a824a57e52,2012-06-21T16:43:42Z,2012-06-21T17:13:42Z,cd6499a0-18fe-4c2c-a8..."
COPY 113
ERROR:  extra data after last expected column
CONTEXT:  COPY medications, line 2: "2010-01-04,2010-12-30,244f6a12-dfe3-4fc4-b77e-ddf5275f21a1,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1e23..."
COPY 1065
ERROR:  extra data after last expected column
CONTEXT:  COPY patients, line 2: "cd6499a0-18fe-4c2c-a88c-3bd630f8e20a,1984-04-13,,999-49-3625,S99964365,X30889808X,Mr.,Leslie90,Rice9..."

**Comment by AnthonyMolinaro** [comment]
As mentioned in issue #38, we're no longer supporting the shell script.
