### ISSUE TITLE
Load Event Tables

### ISSUE THREAD

**Issue by mizu99super** [OHDSI/ETL-Synthea#47]
When I execute Load Event Table command: ETLSyntheaBuilder::LoadEventTables(cd,"cdm_synthea10","native"),
the error below is output.

I think the attribute of provider_id is wrong.
Could you check it?

Thank you for your always support.

**Error:
org.postgresql.util.PSQLException: ERROR: column "provider_id" is of type integer but expression is of type text
ヒント: You will need to rewrite or cast the expression.
位置: 665**

_'ヒント' means tips_
_'位置' means line number_

**Comment by clairblacketer** [comment]
Hi @mizu99super I fixed this issue with the most recent pull request bringing synthea up to v6.0. Essentially the null being set for the provider_id has to be cast as a bigint.

**Comment by anthonysena** [comment]
@clairblacketer - I think this problem is related to some of the changes I made to make ETL-Synthea compatible with CDM v5.3.1 (see #46). Perhaps we should consider tagging a v1.0.0 of ETL-Synthea that is compatible with CDM v5.3.1 and creating a branch for any v5.3.1 fixes from there? Then the master branch can focus on CDM v6.x. I'm happy to help make this happen but wanted to put this idea out there in case others had ideas along these lines.

**Comment by clairblacketer** [comment]
Hi @anthonysena there is a release with tag [v5.3.1](https://github.com/OHDSI/ETL-Synthea/tree/v5.3.1) so we can move forward with this approach. I will say I had this issue when using an older version of the synthea native files to prepare for the symposium. I found that casting the null worked in that instance as well.

**Comment by anthonysena** [comment]
@clairblacketer - sorry to have missed the v5.3.1 tag! Please ignore my previous comment.

**Comment by psbrandt** [comment]
@mizu99super I created a PR that shows what I had to do to get it working on Postgres. You can try my code by replacing `devtools::install_github("OHDSI/ETL-Synthea")` with `devtools::install_github("psbrandt/ETL-Synthea")` in the install instructions.

In case it helps anyone else, [here](https://bintray.com/api/ui/download/phema/omop-data/synthea.1000.cdm.5.3.1.sql.zip) is a dump of the CDM 5.3.1 event tables resulting from using this tool to import 1000 randomly generated Synthea patients. I had the default selected vocabularies loaded from Athena (available [here](http://athena.ohdsi.org/api/v1/vocabularies/zip/26df49cc-8eeb-43fb-87eb-7a45e4f30e6b)) when I ran the ETL.

**Comment by marzbuzz** [comment]
@psbrandt 

I'm trying to load the synthea data in postgreSQL.

I use devtools::install_github("psbrandt/ETL-Synthea") and I got the following error messages. It seems working for the other parts, but when I check the tables in cdm_synthea10 and native schema, all the tables are empty. See attached for the detail. Please let me know how do I troubleshoot this.
 
Error in data.table::fread(file = paste0(syntheaFileLoc, "/", csv), stringsAsFactors = FALSE,  : 
  File '/tmp/synthea/output/csv/allergies.csv' does not exist or is non-readable.
Error in data.table::fread(file = paste0(vocabFileLoc, "/", csv), stringsAsFactors = FALSE,  : 
  File '/tmp/Vocabulary_20181119/concept.csv' does not exist or is non-readable.

![image](https://user-images.githubusercontent.com/45695294/72364739-fb8c7e80-36c4-11ea-8d59-f689782279b1.png)

Thanks for your support. Really appreciated.

**Comment by AnthonyMolinaro** [comment]
@mizu99super Hi, this is fixed in v6.0.  I've created a new branch for 5.3 specific issues: v5.3.1-updates.  I will be applying the fix from @wibeasley to the new branch as soon as the PR is available.  In the future, if you're using cdm 5.3 please work off the v5.3.1-updates branch.  Thanks!
