### ISSUE TITLE
Variable type for dates not correctly rendered to SQL SERVER

### ISSUE THREAD

**Issue by OskarGauffin** [OHDSI/ETL-Synthea#49]
I don't know if ETLSyntheaBuilder is intended to work with other servers than postgresql, but in case anyone tries to use sql server, the following issue needs to be fixed: The code in `ETLSyntheaBuilder::CreateEventTables` (and most likely later queries as well) do not render correctly, as it tries to set TIMESTAMP as class for dates, which should be set to something like DATETIME. 

Running the line ETLSyntheaBuilder::CreateEventTables(*insert your defaults*) gives you this error message:

```
Error in rJava::.jcall(statement, "V", "close") : 
  com.microsoft.sqlserver.jdbc.SQLServerException: A table can only have one timestamp column. Because table 'person' already has one, the column 'death_datetime' cannot be added.
```

After a bit of drilling, you find that two variables in the rendered SQL-table-creation code for person table (and quite a few other tables) are set to TIMESTAMP. 

```
CREATE TABLE cdm_synthea10.person
(
   person_id					BIGINT	  	NOT NULL , 
  gender_concept_id				INTEGER	  	NOT NULL ,
  year_of_birth					INTEGER	  	NOT NULL ,
  month_of_birth				INTEGER	  	NULL,
  day_of_birth					INTEGER	  	NULL,
  birth_datetime				TIMESTAMP	NULL,
  death_datetime				TIMESTAMP     NULL,
  race_concept_id				INTEGER		NOT NULL,
```

TIMESTAMP in sql server is synonym to rowversion, and not at all related to storing data on dates and times.

**Comment by AnthonyMolinaro** [comment]
@OskarGauffin  Hi Oskar, this is fixed in v6.0. I've created a branch for 5.3 specific issues, v5.3.1-updates, and will will be applying the fix for the timestamp issue from @wibeasley to that branch once a new PR is submitted.  Thanks.
