### ISSUE TITLE
Create R project to run the builder

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/ETL-Synthea#5]
There are quite a few sql files for this build, some of which that are no longer being used. An R project would help dictate the order that the files should be run, as well as allowing for parameterization for schemas. We could also put the test cases in the project so that it is entirely self-contained.

**Comment by AnthonyMolinaro** [comment]
@clairblacketer, Agreed.  After discussing with Frank, we're going to maintain two separate versions.  The R version will live in a repo called ETL-SyntheaBuilder (at some point).  : )
