### ISSUE TITLE
Single rows missing concept name, while running LoadVocabFromCsv

### ISSUE THREAD

**Issue by OskarGauffin** [OHDSI/ETL-Synthea#50]
Hello! While inserting the vocabularies with ETLSyntheaBuilder::LoadVocabFromCsv, using vocabularies from athena, merged with the UMLS as instructed, the call stops at two occassions, as rows have NA where there shouldn't be any.

```
vocabTable[3602658,]
   concept_id concept_name  domain_id vocabulary_id concept_class_id standard_concept concept_code valid_start_date
1:   36311145         <NA> Meas Value         LOINC           Answer                S    LA12334-1       1970-01-01
   valid_end_date invalid_reason
1:     2099-12-31   

```
The other row, in concept_synonym.csv:

```
   concept_id concept_synonym_name language_concept_id
1:   36311145                 <NA>             4180186
``` 
I removed these, and LoadVocabFromCsv() ran through after that.

**Comment by clairblacketer** [comment]
Hi @OskarGauffin if you use the function from pull request #48 this is fixed. It is based on how R identifies NULL values. In the case you highlighted above, the concept name is 'NA' but R thinks it is blank.

**Comment by MaximMoinat** [comment]
Ah, just discovered this as well. Good to know it is already fixed.

For reference, the offending 'NA' concept. Took me some time to realise that this was the actual value and not some placeholder. http://athena.ohdsi.org/search-terms/terms/36311145

**Comment by AnthonyMolinaro** [comment]
Thank you Clair and Maxim.
