### ISSUE TITLE
Some concept ID columns are all 0

### ISSUE THREAD

**Issue by greenguy33** [OHDSI/ETL-Synthea#55]
I've run the pipeline using the fork provided by `psbrandt` at https://github.com/psbrandt/ETL-Synthea.  I've used this fork because of the issue described in https://github.com/OHDSI/ETL-Synthea/issues/47.

I spun up a Postgresql instance and followed the steps as described in the README using RStudio. I obtained all non-license required Athena vocabularies from http://athena.ohdsi.org/vocabulary/list and created `native` and `cdm_synthea10` schemas. 

The pipeline ran to completion but the following columns of interest had all of their rows as 0 instead of a relevant OMOP concept id:
- in table `condition_occurrence`: `condition_concept_id`
- in table `drug_exposure`: `drug_concept_id`
- in table `measurement`: `measurement_concept_id`

Is it possible that the code designed to work with an older version of the Athena vocabularies than what I downloaded two days ago? If not, what would be a useful next step towards debugging?

**Comment by greenguy33** [comment]
I was able to solve this issue. Several columns from the Athena vocabulary were expected to be `null` but were in fact blank strings. That is what caused the concept ID's to not populate properly.

**Comment by AnthonyMolinaro** [comment]
Great catch!  We'll keep an eye out for this.
