### ISSUE TITLE
LoadVocabFromCsv ERROR: null value in column "concept_name" violates not-null constraint

### ISSUE THREAD

**Issue by Tinegeldof** [OHDSI/ETL-Synthea#57]
While following the steps on the _Step by Step Example_ in the read me, I encountered a problem during the `ETLSyntheaBuilder::LoadVocabFromCsv(cd,"cdm_synthea10","/tmp/Vocabulary_20181119") `step

#13 mentioned this issue and avoided it by "allowing NULLs in concept.concept_name, concept.concept_code, concept_synonym.concept_synonym_name, and concept_relationship.valid_start_date."

How should I allow for these NULLS? Does LoadVocabFromCsv.r needs to be adapted?

I am using the latest pull of the master with vocabulary v5

**Comment by scivm** [comment]
I used this file from one of the existing pull requests to get rid of these.

https://github.com/clairblacketer/ETL-Synthea/blob/master/R/LoadVocabFromCsv.r

But you dont want the full pull request because it is omop 6.

**Comment by Tinegeldof** [comment]
Thank you for your help!
