### ISSUE TITLE
v5.3.1 misspelled column name

### ISSUE THREAD

**Issue by alondhe** [OHDSI/ETL-Synthea#62]
revenue_code_source_value is misspelled here:

https://github.com/OHDSI/ETL-Synthea/blob/v5.3.1/inst/sql/sql_server/create_event_tables.sql#L511

**Comment by AnthonyMolinaro** [comment]
Thanks Ajit.  

Since master is on cdm 6.0, I've created a new branch based on the v5.3.1 release: [v5.3.1-updates](https://github.com/OHDSI/ETL-Synthea/tree/v5.3.1-updates)

.. to address 5.3 issues. I'm applied the fix there.
