### ISSUE TITLE
duplicate key error in insert_measurement.sql, others for postgresql

### ISSUE THREAD

**Issue by chrisroederucdenver** [OHDSI/ETL-Synthea#67]
I ran into a duplicate key error when running insert_measurement and others. I saw the union of two or three selects that use row_number(), and guessed each where starting from 1. I recreated the sequences and replaced the row_number() calls with nextval, and the problem went away. I assume these were added to give databases a chance to run the individual selects concurrently and that re-introducing use of the sequence would serialize and slow down the insert.

The commit that introduced the use of row_number() is b282d802.

**Comment by fdefalco** [comment]
resolved in the v5.3.1_updates branch
