### ISSUE TITLE
Synthea has added additional cost columns to Patient, Medication, and Encounter tables--breaks bulk-load

### ISSUE THREAD

**Issue by mmtrun** [OHDSI/ETL-Synthea#70]
It appears that the CSV output from Synthea now contains additional columns relating to cost of encounters and medications, and total healthcare expenses to patients. These columns are not created in the native synthea schema by the ETL-Synthea DDL. As a result, bulk-load fails for these three tables, viz.,

ERROR:  extra data after last expected column
CONTEXT:  COPY encounters, line 2: "1010abf7-397f-8393-9ff0-2c16c1058605,2011-06-20T04:44:41Z,2011-06-20T04:59:41Z,8c2ec300-a8d1-0e5e-88..."

**Comment by podalv** [comment]
Same problem here. Is this project abandoned? Should I fork this and fix ?

**Comment by fdefalco** [comment]
No, the project hasn't been abandoned.  Sorry this issue got overlooked.  We would welcome a pull request otherwise we'll get it in queue to be fixed.

**Comment by podalv** [comment]
OK, that's good to hear. I have fixed the issue but I am seeing errors in the latter portions of the pipeline. Do you want me to issue a pull request for this issue and start a ticket for the other ones?

**Comment by AnthonyMolinaro** [comment]
@mmtrun Hi Matthew, the updates proposed by @podalv were pushed to Master.  Please note, we are no longer maintaining the bulk load version of the builder and will only be maintaining the R implementation. Thanks for submitting this issue!
