### ISSUE TITLE
Where are the Vocabulary CSVs?

### ISSUE THREAD

**Issue by zhiboz** [OHDSI/ETL-Synthea#72]
Where does the repo get the Vocabulary CSV files from? Thanks very much!

**Comment by chrisroederucdenver** [comment]
It’s a little more involved. You have to select the vocabularies you’d like to include and have a set built. Download them when notified.

https://athena.ohdsi.org/vocabulary/list

**Comment by zhiboz** [comment]
thanks a lot for your prompt response!
