### ISSUE TITLE
CDM_SOURCE Enhancement

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/ETL-Synthea#75]
@AnthonyMolinaro - 

https://github.com/OHDSI/ETL-Synthea/blob/43215520bbfcca0fe2310ab65dccae4e081d1e57/inst/sql/sql_server/insert_cdm_source.sql

Could we enhance CDM_SOURCE to do the following:

- pull the VOCABULARY_VERSION from the Vocabulary 
```
SELECT VOCABULARY_VERSION
FROM VOCABULARY
WHERE VOCABULARY_ID = 'None'
```
- Set the CDM_RELEASE_DATE to GETDATE()
- Make a comment next to SOURCE_RELEASE_DATE that to set this value to the day the data was pulled

I would like to use it as an example in EHDEN.

Tagging @clairblacketer

**Comment by AnthonyMolinaro** [comment]
You can mess with the Hoff, but not with the Voss.
