### ISSUE TITLE
Error while LoadVocabFromCsv

### ISSUE THREAD

**Issue by mgabetta** [OHDSI/ETL-Synthea#79]
Now, during:
`ETLSyntheaBuilder::LoadVocabFromCsv(connectionDetails = cd, cdmSchema = cdmSchema, vocabFileLoc = vocabFileLoc)`

I get this error:
`java.sql.BatchUpdateException: Batch entry 287 INSERT INTO omop_synthea.concept (concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason) VALUES(36311145,NULL,'Meas Value','LOINC','Answer','S','LA12334-1','1970-01-01 +01','2099-12-31 +01',NULL) was aborted: ERROR: null value in column "concept_name" violates not-null constraint`

but the line from the concept.csv file is:
`36311145	NA	Meas Value	LOINC	Answer	S	LA12334-1	19700101	20991231`

Any ideas why NA in the source is interpreted as NULL (thus violating NOT NULL constraint in db)?

**Comment by AnthonyMolinaro** [comment]
@mgabetta Hi again. : )

NA in R is a way to represent missing data.  So, when a file with a missing value or NA is being loaded it will be inserted as NULL into the CDM.   This functionality was necessary to address issue #73 .  Empty string fields or NAs in the data should not result in empty strings, '', being inserted into the CDM, but should explicitly be NULL. To explain it another way, suppose your line of data were the following:

`NA 36311145 Meas Value LOINC Answer S LA12334-1 19700101 20991231`

Now, concept_id is NA and the concept_name is a string of numbers.  How would NA in a numeric field translate to something SQL could understand?  It must be NULL.

If for testing purposes you're trying to use the string literal 'NA' as the concept_name in your example, you would need to modify the data to treat that NA as just a string that happens to include the letters N and A.

Thanks for your feedback thus far, it has been really helpful!

**Comment by mgabetta** [comment]
Ok thanks!
The point is that 'NA's that I'm using (like the one in the example) come from the plain athena.ohdsi.org export and have not been modified by me for testing purpose. Thus, it may become a common issue for those that will try it.
A solution may be to manage the exception in the LoadVocabFromCsv.r function.

**Comment by AnthonyMolinaro** [comment]
@mgabetta Yeah, I get what you're saying.  I just made an update so that if the string NA is in your file, it will be treated like a string and no longer considered NULL when inserted into the CONCEPT table.  I need to modify this function further because: 1. The file name has "csv" in it, but a tab is used as a separator, so that needs to be changed and 2. It seems that the last column in the CONCEPT file, INVALID_REASON is being inserted as the string NA instead of NULL.  So, work needs to be done on this function.

**Comment by AnthonyMolinaro** [comment]
@mgabetta  Actually, the vocab files are downloaded as .csv files, so the name of the function is fine.  As for INVALID_REASON, it is being handled correctly now (I misunderstood some output from RStudio).  I made one final update as the dplyr call to convert "" to NA is no longer needed if we correctly specify na.strings.  Please let us know how it looks now.
