### ISSUE TITLE
Condition Records Dropped if Mapped to 0

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/ETL-Synthea#8]
In RAW_LAUREN, I accidentally used a CONCEPT_ID for the CODE.  

CODE = `194696`  (INCORRECT CODE AND WOULDN'T HAVE MAPPED TO ANYTHING)
DESCRIPTION = `Dysmenorrhea`

The records were dropped in the CDM.  The record should still be written and just set to CONDITION_CONCEPT_ID = 0.

**Comment by clairblacketer** [comment]
fixed in latest commit
