### ISSUE TITLE
Error in substr(tableName, 1, 1) :  argument "tableName" is missing, with no default when running ETLSyntheaBuilder::LoadSyntheaTables

### ISSUE THREAD

**Issue by phorvicheka** [OHDSI/ETL-Synthea#86]
Hello everyone,

I have run commands in screenshot as the instruction in readme file:
![image](https://user-images.githubusercontent.com/16742458/110934380-49585180-8371-11eb-8560-4154611e30ef.png)

I got Error in substr(tableName, 1, 1) :  argument "tableName" is missing, with no default when running ETLSyntheaBuilder::LoadSyntheaTables.

Error:
![image](https://user-images.githubusercontent.com/16742458/110933705-76f0cb00-8370-11eb-9300-c46f5556534c.png)

![image](https://user-images.githubusercontent.com/16742458/110935215-78bb8e00-8372-11eb-9065-1bf79be80858.png)

Fixed by adding tableName= in front of paste0:
DatabaseConnector::insertTable(conn,tableName=paste0(syntheaSchema,".",strsplit(csv,"[.]")[[1]][1]), data=as.data.frame(syntheaTable), dropTableIfExists = FALSE, createTable = FALSE, progressBar = TRUE)
![image](https://user-images.githubusercontent.com/16742458/110933932-b7504900-8370-11eb-9801-9a96cf716be1.png)

I am not R developer. I manage to make it work by adding tableName= in front of paste0 in R\LoadSyntheaTables.r. But, I don't know whether it is a bug or I miss configure something.

Thank you.

**Comment by AnthonyMolinaro** [comment]
@phorvicheka This is due to the recent update to DatabaseConnector.  I'll push a fix now (essentially, your fix).  :) 
Thanks for letting us know!

**Comment by phorvicheka** [comment]
@AnthonyMolinaro Thank you very much, Sir.
