### ISSUE TITLE
Issue with bulkloading in postgres

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/ETL-Synthea#87]
All the functions that load data (LoadSyntheaTables, LoadVocabTables, etc) set the bulkload option in DatabaseConnectore::insertTable function to TRUE. Per the documentation:

> PostgreSQL: Uses the 'pg' executable to upload. Set the POSTGRES_PATH environment variable to the Postgres binary path, e.g. 'C:/Program Files/PostgreSQL/11/bin'.

The bulkload setting caused my uploads using postgres to fail. When I set it to FALSE then I was able to upload my files to the server. Is this an issue on my part or should we add an option to pass a FALSE to this setting in the load functions?

Edit- I am using DatabaseConnector 4.0 which may contribute to this issue

**Comment by AnthonyMolinaro** [comment]
@clairblacketer  Thanks for the heads up.  I'll modify the necessary functions to allow someone to pass in a TRUE/FALSE flag for bulk loading.
