### ISSUE TITLE
Missing "date" column in procedures during LoadSyntheaTables

### ISSUE THREAD

**Issue by oneilsh** [OHDSI/ETL-Synthea#88]
Hi, I'm attempting to ETL the COVID-19 100K CSV dataset at https://synthea.mitre.org/downloads and getting an error `ERROR:  column "date" of relation "procedures" does not exist`. This seems related to #82 and that the dataset was created with an older version of Synthea. 

I managed to get it to work by renaming the "DATE" column to "START" in procedures.csv, but I thought I'd flag it in case others run across this issue. Perhaps there's a way to support older and newer Synthea outputs, or make the error more informative?

**Comment by fdefalco** [comment]
Thanks for pointing this out.  We've gotten ahead of ourselves here in ETL-Synthea and are testing from the current Synthea repository master branch and recently made that update in #82 in support of that change.  We're going to create a new release parameter for "latest" or "master" for the Synthea version and maintain compatibility with the 2.7 release (and the prior column name) which should resolve if you have to rerun your ETL.  Thanks for the feedback!
