### ISSUE TITLE
Which vocabulary files are needed?

### ISSUE THREAD

**Issue by mpreusse** [OHDSI/ETL-Synthea#89]
I'm trying to load some Synthea data into OMOP CDM.

Is there some documentation on the required vocabularies? For testing purposes it would be easier to work with the minimal set of terminologies in the vocabulary.

**Comment by AustinWalsh** [comment]
I had the same question, I suspect it requires one to go to Athena, then download all available files. Full disclosure, I have not yet made it work either @mpreusse. @AnthonyMolinaro seems to be active in this perhaps he can point us in the right direction?

**Comment by mpreusse** [comment]
@AustinWalsh I got the ETL process working, I downloaded the default set from Athena. I was just wondering if it's possible to limit it further, just to reduce size of the vocabularies.

I put the synthe data generator and the Synthea-ETL tool in Docker containers: https://github.com/kaiserpreusse/synthea2omop. Maybe useful for you?

It's not fully tested and documented but I managed to ETL some Synthea data to OMOP in a Postgres DB.

**Comment by AnthonyMolinaro** [comment]
@mpreusse , @AustinWalsh , This is something we'd like to implement.  @fdefalco and I have discussed this and have kicked around some ideas.  One question is, how do you define "minimal vocabulary"?  If your synthea data are generated via `./run_synthea -p 100`  then your minimal vocabulary would be one that supports ALL the events that came out of that call (including support for death).  Otoh, if you explicitly specified some module (say, diabetes), then your minimal vocabulary would be only that part of the vocabulary necessary to support that module.  I believe @fdefalco  had some ideas around using the synthea json to then trim the vocabulary before you load it.  I'm probably butchering his idea, I'll let him clarify.  : )

**Comment by mpreusse** [comment]
@AnthonyMolinaro thank you for fixing #90 in such short time! 

This should have been a question to the Synthea forum because this obviously depends on the vocabularies used to generate the Synthea output. 

Good to hear that you discussed this already. If possible I'd be happy to help out @fdefalco

**Comment by fdefalco** [comment]
Yes, I've been thinking about 'Vocabulary Shards' or small fragments of the vocabulary that would be required to run the conversion.  One positive of using Synthea is that they generally use the same standard concept types (SNOMED) so there is less mapping that is necessary, but I fully appreciate why this would be helpful.  I had seen that Synthea has an interesting command listed in their readme:

Concepts and Attributes
Generate a list of concepts (used in the records) or attributes (variables on each patient).

./gradlew concepts
./gradlew attributes

Which is supposed to generate a listing of concepts, I haven't had the chance to run it yet.  If someone gets to it before me I would be interested in the output and if it would potentially lead us to the required concepts we would need to get from the vocabulary.  If it did, we could work with Odysseus to get an API to obtain an extract of vocabulary on the basis of a set of concept codes.

**Comment by Iain-S** [comment]
One way to work out which vocabularies are needed is to look for sections of the modules JSON files that look like 

```json
      "codes": [
        {
          "system": "SNOMED-CT",
          "code": 21719001,
          "display": "SNOMED code",
          "value_set": ""
        }
      ],
```

If I look for all occurrences of `"system"` in the modules directory, I get

```bash
grep -e '"system"' -r build/resources/main/modules -h \  # Look for "system"
| sed 's/ //g' \  # Remove whitespace
| sort \  # sort alphabetically
| uniq  # remove duplicates
```
```bash
"system":"DICOM-DCM",
"system":"DICOM-SOP",
"system":"LOINC",
"system":"NUBC",
"system":"RxNorm",
"system":"SNOMED-CT",
```

I think that the `OMOP Xxx` vocabs are probably also needed (`OMOP Gender`, `OMOP Episode Type`, etc).

**Comment by burrowse** [comment]
Closing and will revisit concept of vocabulary shards/minimally required vocabularies in a future release
