### ISSUE TITLE
No column pr.start for insert_measurement

### ISSUE THREAD

**Issue by oneilsh** [OHDSI/ETL-Synthea#93]
Getting closer! I'm working on the LoadEventTables step. Since some of the steps take quite (but the function likes to start from a clean slate, it errors if I try re-running without clearing out all the event tables) I'm using the `sqlOnly` option and running the scripts in the order generated.

```
ETLSyntheaBuilder::LoadEventTables(connectionDetails = cd, cdmSchema = cdmSchema, syntheaSchema = syntheaSchema, cdmVersion = cdmVersion, sqlOnly = TRUE)
```

When running `psql -d synthea10 -f insert_measurement.sql` I get the following error:

```
psql:insert_measurement.sql:131: ERROR:  column pr.start does not exist
LINE 47:   pr.start                                 measurement_date,
           ^
```

**Comment by AnthonyMolinaro** [comment]
@oneilsh 
Good catch Shawn, thanks!
Looks like when I applied the fix for issue #88 , I updated insert_procedure_occurrence.sql but missed insert_measurement.sql.  I'll get a fix into Master today.
