### ISSUE TITLE
insert_device_exposure.sql value too long

### ISSUE THREAD

**Issue by oneilsh** [OHDSI/ETL-Synthea#94]
When running `insert_device_exposure.sql` (generated by `ETLSyntheaBuilder::LoadEventTables(connectionDetails = cd, cdmSchema = cdmSchema, syntheaSchema = syntheaSchema, cdmVersion = cdmVersion, sqlOnly = TRUE)`)

```
psql:insert_device_exposure.sql:52: ERROR:  value too long for type character varying(50)
```

**Comment by fdefalco** [comment]
We resolved this in the v5.3.1_fixes branch of the CommonDataModel repository. There is a parameter you can pass to use that reference branch (v5.3.1_fixes) instead of the default which should resolve this error.

https://github.com/OHDSI/ETL-Synthea/blob/master/R/CreateCDMTables.r#L26-L31

**Comment by oneilsh** [comment]
Thanks @fdefalco  Do I need to drop all the tables to repopulate them with the updated schema, since it's in the earlier CreateCDMTables step?

**Comment by AnthonyMolinaro** [comment]
@oneilsh Yes, you'll need to drop and recreate (there is a function to drop only the event tables so you don't need to reload the vocab each time).
