### ISSUE TITLE
R package needed

### ISSUE THREAD

**Issue by rwayne** [OHDSI/ETL-Synthea#96]
ETLSyntheaBuilder  - Sorry if I missed this in the documentation but what package is required.  I tried R 4.x and now "package ‘ETLSyntheaBuilder’ is not available (for R version 3.6.3)"

thank you.  Appreciate this work.

**Comment by fdefalco** [comment]
Are you cloning the repository and building locally or installing using devtools?

**Comment by rwayne** [comment]
Downloaded the repo and then installing R and R Studio


cd <- DatabaseConnector::createConnectionDetails(
  dbms     = "x1",
  server   = ".unx.sas.com",
  user     = "xx",
  password = "x",
  port     = 5432,
   pathToDriver = "C:\\temp\\" ,
)

pathToDriver = "C:\\Users\\sasrwt\\


cdmSchema      <- "cdm_synthea10"
cdmVersion     <- "5.3.1"
syntheaVersion <- "2.7.0"
syntheaSchema  <- "native"
syntheaFileLoc <- 'c:\\Users\\sasrwt\\synthea\\output\\csv'
vocabFileLoc   <- "C:\\temp\\"

**Comment by fdefalco** [comment]
If you have cloned the repo, you have to do a local build in R studio for the package to be available.

**Comment by rwayne** [comment]
Thanks Frank for responding. I am having trouble synching Java and Rjava.


When running:
devtools::install_github("OHDSI/ETL-Synthea")


Error: package or namespace load failed for 'DatabaseConnector':
.onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error : package 'DatabaseConnector' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/sasrwt/Documents/R/win-library/3.6/ETLSyntheaBuilder'

**Comment by fdefalco** [comment]
It looks like you have the 32 bit version of R installed along with the 64 bit version, but only one version of the Java SDK.  I suggest uninstalling and following the instructions available here for configuring your environment:

https://ohdsi.github.io/Hades/rSetup.html

**Comment by rwayne** [comment]
Thanks Frank.   I am running R Studio 64 bit with a 64 bit Java JDK  making sure that

Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk1.8.0_291/")

Looks like I am running into this issue:

https://stackoverflow.com/questions/13311107/build-r-package-failing-with-rjava-loadlibrary-not-a-valid-win32-application-f


Do you know how to run this?



 R --verbose CMD check --no-multiarch messageQueue_0.1.tar.gz


Error: package or namespace load failed for 'DatabaseConnector':
.onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/sasrwt/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'DatabaseConnector' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/sasrwt/Documents/R/win-library/3.6/ETLSyntheaBuilder'
Warning message:
In i.p(...) :
  installation of package 'C:/Users/sasrwt/AppData/Local/Temp/RtmpIPk37Z/file199015f65ad1/ETLSyntheaBuilder_0.1.0.tar.gz' had non-zero exit status

**Comment by rwayne** [comment]
I've made some progress:  Clean install with just 64 bit R is working.



When running:  ETLSyntheaBuilder::CreateCDMTables(connectionDetails = cd, cdmSchema = cdmSchema, cdmVersion = cdmVersion)

I get

r: Error executing SQL:org.postgresql.util.PSQLException: ERROR: schema "cdm_synthea10" does not exist
Position: 14
An error report has been created at C:/Users/sasrwt/Documents/errorReportSql.txt
Run `rlang::last_error()` to see where the error occurred.

The synthea csv files are provided to me by another user.  Where do I identify the right schema?



From: Wayne Thompson
Sent: Saturday, May 1, 2021 8:44 AM
To: OHDSI/ETL-Synthea ***@***.***>; OHDSI/ETL-Synthea ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [OHDSI/ETL-Synthea] R package needed (#96)

Thanks Frank.   I am running R Studio 64 bit with a 64 bit Java JDK  making sure that

Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk1.8.0_291/")

Looks like I am running into this issue:

https://stackoverflow.com/questions/13311107/build-r-package-failing-with-rjava-loadlibrary-not-a-valid-win32-application-f


Do you know how to run this?



 R --verbose CMD check --no-multiarch messageQueue_0.1.tar.gz


Error: package or namespace load failed for 'DatabaseConnector':
.onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/sasrwt/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'DatabaseConnector' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/sasrwt/Documents/R/win-library/3.6/ETLSyntheaBuilder'
Warning message:
In i.p(...) :
  installation of package 'C:/Users/sasrwt/AppData/Local/Temp/RtmpIPk37Z/file199015f65ad1/ETLSyntheaBuilder_0.1.0.tar.gz' had non-zero exit status

**Comment by rwayne** [comment]
Please disregard.  I finally got the name of the schema.  You have been very patient and helpful.  Your package will be very useful

From: Wayne Thompson
Sent: Monday, May 3, 2021 2:12 PM
To: OHDSI/ETL-Synthea ***@***.***>; OHDSI/ETL-Synthea ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [OHDSI/ETL-Synthea] R package needed (#96)

I've made some progress:  Clean install with just 64 bit R is working.



When running:  ETLSyntheaBuilder::CreateCDMTables(connectionDetails = cd, cdmSchema = cdmSchema, cdmVersion = cdmVersion)

I get

r: Error executing SQL:org.postgresql.util.PSQLException: ERROR: schema "cdm_synthea10" does not exist
Position: 14
An error report has been created at C:/Users/sasrwt/Documents/errorReportSql.txt
Run `rlang::last_error()` to see where the error occurred.

The synthea csv files are provided to me by another user.  Where do I identify the right schema?



From: Wayne Thompson
Sent: Saturday, May 1, 2021 8:44 AM
To: OHDSI/ETL-Synthea ***@***.******@***.***>>; OHDSI/ETL-Synthea ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [OHDSI/ETL-Synthea] R package needed (#96)

Thanks Frank.   I am running R Studio 64 bit with a 64 bit Java JDK  making sure that

Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jdk1.8.0_291/")

Looks like I am running into this issue:

https://stackoverflow.com/questions/13311107/build-r-package-failing-with-rjava-loadlibrary-not-a-valid-win32-application-f


Do you know how to run this?



 R --verbose CMD check --no-multiarch messageQueue_0.1.tar.gz


Error: package or namespace load failed for 'DatabaseConnector':
.onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/sasrwt/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'DatabaseConnector' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/sasrwt/Documents/R/win-library/3.6/ETLSyntheaBuilder'
Warning message:
In i.p(...) :
  installation of package 'C:/Users/sasrwt/AppData/Local/Temp/RtmpIPk37Z/file199015f65ad1/ETLSyntheaBuilder_0.1.0.tar.gz' had non-zero exit status

**Comment by fdefalco** [comment]
Glad to hear you have it working.
