### ISSUE TITLE
syntheaFileLoc = syntheaFileLoc

### ISSUE THREAD

**Issue by rwayne** [OHDSI/ETL-Synthea#97]
Able to run the first 2 ETL commands and also load the vocabulary files.  

I have syntheaFileLoc set to - 'c:\\Users\\sasrwt\\synthea\\output\\csv'  but am getting this error in the path where the Synthea files are located?  Forward slash.   I am running 64 bit Windows.  Within the csv folder there a folders for each entry as you likely know.  How can I define the path to  read in the data with each subfolder of the output folder?  Followed example syntheaFileLoc convention.  

> ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaFileLoc = syntheaFileLoc)
Connecting using PostgreSQL driver
Error in data.table::fread(file = paste0(syntheaFileLoc, "/", csv), stringsAsFactors = FALSE,  : 
  File 'c:\Users\sasrwt\synthea\output\csv/allergies.csv' does not exist or is non-readable. getwd()=='C:/Users/sasrwt/Documents/OMOP'
>

**Comment by AnthonyMolinaro** [comment]
@rwayne  Hi Wayne,

In an R session on your windows platform, please try the following and share the results:

```r
syntheaFileLoc <- "C:/Users/sasrwt/synthea/output/csv"
list.files(syntheaFileLoc)
```
Thanks.

**Comment by rwayne** [comment]
Hi Anthony,

Any update?  On windows I am still getting the same issue as reported - https://github.com/OHDSI/ETL-Synthea/issues/97

On linux I get this error but there subdirectories with the csv files are there.   Would you be open to a short teams or google meeting?

***@***.***D7471E.DB1052B0]
From: Wayne Thompson
Sent: Tuesday, May 11, 2021 2:39 PM
To: OHDSI/ETL-Synthea ***@***.***>; OHDSI/ETL-Synthea ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OHDSI/ETL-Synthea] syntheaFileLoc = syntheaFileLoc (#97)

Thanks much.   I am also working with my team on the POSTGRES credentials.

***@***.***D7471E.DB1052B0]

**Comment by AnthonyMolinaro** [comment]
@rwayne  Hi Wayne,

Tell help me diagnose the issue, can you run the following and post the results here?

```r
syntheaFileLoc <- "C:/Users/sasrwt/synthea/output/csv"
list.files(syntheaFileLoc)
```
I made a similar request for the unix question as well.
Thanks.

**Comment by rwayne** [comment]
Yes I sent that via an image.   Thanks for your help. Here it is cut and paste from Rstudio

Unix:
Executing SQL took 0.0711 secs
> ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaFileLoc = syntheaFileLoc)
Connecting using PostgreSQL driver
Error in data.table::fread(file = paste0(syntheaFileLoc, "/", csv), stringsAsFactors = FALSE,  :
  File '/data/sasrwt/Synthea/output/csv//allergies.csv' does not exist or is non-readable. getwd()=='/r/sanyo.unx.sas.com/vol/vol210/u21/sasrwt'
> syntheaFileLoc <- "/data/sasrwt/Synthea/output/csv/"
> list.files(syntheaFileLoc)
[1] "2021_04_20T14_36_41Z" "2021_04_21T12_49_35Z" "2021_04_21T12_53_37Z" "2021_04_21T12_57_23Z" "2021_04_21T13_00_46Z" "2021_04_21T13_05_09Z"
[7] "2021_04_21T13_24_48Z" "2021_04_21T15_20_02Z" "2021_04_21T15_35_51Z" "2021_04_21T15_42_04Z"
>

**Comment by AnthonyMolinaro** [comment]
@rwayne  Thanks for the copy/paste, for some reason my browser isn't rendering your image.

Ok, so if the output of 
```r 
list.files(syntheaFileLoc)
``` 
is:
```r
[1] "2021_04_20T14_36_41Z" "2021_04_21T12_49_35Z" "2021_04_21T12_53_37Z" "2021_04_21T12_57_23Z" "2021_04_21T13_00_46Z" "2021_04_21T13_05_09Z"
[7] "2021_04_21T13_24_48Z" "2021_04_21T15_20_02Z" "2021_04_21T15_35_51Z" "2021_04_21T15_42_04Z"
```
... then the error is caused by the .csv files not being present in syntheaFileLoc.  When you execute LoadSyntheaTables, the parameter, syntheaFileLoc, should point to the location of the .csv files you want to load.  The function is expecting to find files like allergies.csv, but as list.files(syntheaFileLoc) reveals, they aren't there.  Copy the synthea csv files to syntheaFileLoc and see if list.file(syntheaFileLoc) finds them.  If so, LoadSyntheaTables should work.

**Comment by rwayne** [comment]
Current issue:


Each of these folders contain the underlying csv files like allergies

Subfolder name:   2021_04_20T14_36_41Z
                First 2 records of allergies from this folder
1988-02-05,,a7981191-4d77-e82d-3633-f61a941945a1,aef40781-c9b7-b707-0148-cc737990aae4,419474003,Allergy to mould
1988-02-05,,a7981191-4d77-e82d-3633-f61a941945a1,aef40781-c9b7-b707-0148-cc737990aae4,419263009,Allergy to tree pollen


Subfolder name:  2021_04_21T12_49_35Z
First 2 records

1971-05-11,,3230504f-beba-308a-9ed9-e7e5c8d179e9,1593e6d5-66e2-c3d4-803f-c9e704527cca,419474003,Allergy to mould
1971-05-11,,3230504f-beba-308a-9ed9-e7e5c8d179e9,1593e6d5-66e2-c3d4-803f-c9e704527cca,232347008,Dander (animal) allergy


This is what synthea outputs to the output/csv   folder.  Subdirectories

I thought you package read the underlying files from each subfolder.  Does it expect just one set of csv file at the root level ?


Related Issue:

So I go back to synthea and run a much simpler run.

java -jar synthea-with-dependencies.jar -p 20 -a 50-120


Now I have just the csv files at the syntheafileloc
> list.files(syntheaFileLoc)
[1] "allergies.csv"         "careplans.csv"         "conditions.csv"        "devices.csv"           "encounters.csv"        "imaging_studies.csv"
 [7] "immunizations.csv"     "medications.csv"       "observations.csv"      "organizations.csv"     "patients.csv"          "payer_transitions.csv"
[13] "payers.csv"            "procedures.csv"        "providers.csv"         "supplies.csv"


I do get an error loading the procedures.csv

ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaFileLoc = syntheaFileLoc)
Connecting using PostgreSQL driver
Loading: allergies.csv
  |===========================================================================================================================================================| 100%
Loading: conditions.csv
  |===========================================================================================================================================================| 100%
Loading: imaging_studies.csv
  |===========================================================================================================================================================| 100%
Loading: medications.csv
  |===========================================================================================================================================================| 100%
Loading: organizations.csv
  |===========================================================================================================================================================| 100%
Loading: procedures.csv
  |                                                                                                                                                           |   0%java.sql.BatchUpdateException: Batch entry 0 INSERT INTO rweapp_t.procedures (START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION) VALUES('2014-02-07 -05','2014-02-07 -05','9a81e6e7-2156-bc98-6099-e22a963c7d66','61828cbb-5f3a-0cd7-22eb-d06ae53f87ce','229064008','Movement therapy (regime/therapy)',516.65,NULL,NULL) was aborted: ERROR: column "start" of relation "procedures" does not exist
  Position: 34  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:862)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
        at org.ohdsi.databaseConnector.BatchedInsert.executeBatch(BatchedInsert.java:114)
Caused by: org.postgresql.util.PSQLException: ERROR: column "start" of relation "procedures" does not exist
  Position: 34
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:859)
        ... 3 more
ERROR: column "start" of relation "procedures" does not exist
 Position: 34
  |===========================================================================================================================================================| 100%
Loading: careplans.csv
  |===========================================================================================================================================================| 100%
Loading: encounters.csv
  |===========================================================================================================================================================| 100%
Loading: immunizations.csv
  |===========================================================================================================================================================| 100%
Loading: observations.csv
  |===========================================================================================================================================================| 100%
Loading: patients.csv
  |===========================================================================================================================================================| 100%
Loading: providers.csv
  |===========================================================================================================================================================| 100%
Loading: devices.csv
  |==========================

**Comment by AnthonyMolinaro** [comment]
@rwayne Glad we're making progress.  : )

>  Does it expect just one set of csv file at the root level ?

Yes.

Regarding the error, 
```r
ERROR: column "start" of relation "procedures" does not exist
```
... this is because Synthea changed a date column in the PROCEDURES table from "date" to "start".  It looks like the version of synthea you have is the latest, so you should specify:
```r
syntheaVersion <- "master"
```
We allow you to specify the Synthea version so you can use an older version or the current version (because Synthea actively updates their Master branch, we decided to let 2.7.0 be the default).  Unfortunately, you'll need to drop the Synthea tables and recreate them using CreateSyntheaTables, this time specifying syntheaVersion <- "master".

**Comment by rwayne** [comment]
Able to load the synthea files. 😊

Now having trouble loading the vocabulary files.


> ETLSyntheaBuilder::LoadVocabFromCsv(connectionDetails = cd, cdmSchema = cdmSchema, vocabFileLoc = vocabFileLoc)
Connecting using PostgreSQL driver
Error in data.table::fread(file = paste0(vocabFileLoc, "/", csv), stringsAsFactors = FALSE,  :
  File '/data/sasrwt/vocab/concept.csv' does not exist or is non-readable. getwd()=='/r/sanyo.unx.sas.com/vol/vol210/u21/sasrwt'
> vocabFileLoc <- "/data/sasrwt/vocab"
> list.files(vocabFileLoc)
[1] "CONCEPT_ANCESTOR.csv"     "CONCEPT_CLASS.csv"        "CONCEPT_CPT4.csv"         "CONCEPT_RELATIONSHIP.csv"
[5] "CONCEPT_SYNONYM.csv"      "CONCEPT.csv"              "DOMAIN.csv"               "DRUG_STRENGTH.csv"
 [9] "Encoding Time.csv"        "RELATIONSHIP.csv"         "VOCABULARY.csv"
>
>

**Comment by AnthonyMolinaro** [comment]
@rwayne  Interesting.  I wonder if the file names are case sensitive on unix, but not windows.  Can you try it on your windows box?

**Comment by rwayne** [comment]
Hi Anthony,

Changed the vocab files from Athean to lowercase and now your ETL tool is importing the vocabs.

> ETLSyntheaBuilder::LoadVocabFromCsv(connectionDetails = cd, cdmSchema = cdmSchema, vocabFileLoc = vocabFileLoc)
Connecting using PostgreSQL driver
|--------------------------------------------------|
|==================================================|
Loading: concept.csv
  |===========================================================================================================================| 100%
Loading: vocabulary.csv
  |===========================================================================================================================| 100%
Loading: concept_ancestor.csv
  |====================


Thanks much Wayne

**Comment by AnthonyMolinaro** [comment]
@rwayne  Thanks for the update and glad things are working now. : )

The code shouldn't break because of the case of the file names, so I'm going to work on a fix now and push it to Master shortly.
