### ISSUE TITLE
SyntheaFileloc Issue

### ISSUE THREAD

**Issue by rwayne** [OHDSI/ETL-Synthea#98]
I switched over to a unix environment to hopefully overcome the path location I was having on Windows (reported separately).  

I run:
ETLSyntheaBuilder::LoadSyntheaTables(connectionDetails = cd, syntheaSchema = syntheaSchema, syntheaFileLoc = syntheaFileLoc)
Connecting using PostgreSQL driver
Error in data.table::fread(file = paste0(syntheaFileLoc, "/", csv), stringsAsFactors = FALSE,  : 
  File '/data/sasrwt/SyntheaFiles/allergies.csv' does not exist or is non-readable. getwd()=='/r/sanyo.unx.sas.com/vol/vol210/u21/sasrwt'

I have subfolders in the synthea file location 
syntheaFileLoc <- "/data/sasrwt/SyntheaFiles"
vocabFileLoc   <- "/data/sasrwt/vocab"

It is still only looking at the root directory. Synthea outputs a separate directory for each patient. 

 Run this 
cd <- DatabaseConnector::createConnectionDetails(
   dbms = "postgresql", 
  server   = "xxxx.unx.sas.com/rwx", 
  user     = "rwx", 
  password = "rwx", 
  port     = 5432,
  pathToDriver = "/opt/postgresql/driver/"
  )

2.	
cdmSchema      <- "rweapp_5"
cdmVersion     <- "5.3.1"
syntheaVersion <- "2.7.0"
syntheaSchema  <- "rweapp_5"
syntheaFileLoc <- "/data/sasrwt/SyntheaFiles"
vocabFileLoc   <- "/data/sasrwt/vocab"

**Comment by AnthonyMolinaro** [comment]
@rwayne  Hi Wayne,

Thanks for listing the Windows and Unix issues separately, makes it easier to work through.  : )

Please list the output from the following commands from your R session:

```r
syntheaFileLoc
list.files(syntheaFileLoc)
```
Thanks.
